### ISSUE TITLE
does this work?  

### ISSUE THREAD

**Issue by Skeyelab** [andskli/zendesk_automator#1]
I downloaded this as is, but can't really get it to do anything.

Does this work as is?

**Comment by andskli** [comment]
Yes, but you have to build it yourself.

Exec:

```
bundle exec rake build
```

And it generates the gem file in `pkg/`. You should then be able to `gem install pkg/zendesk_automator-X.Y.Z.gem`. I just bumped the version for you and merged that into master along with a few other minor fixes. So I'd recommend that you fetch the updates.

Please tell me how it works out for you, happy to help.

**Comment by andskli** [comment]
@Skeyelab also note that there's no daemon built in just yet. I'm running it using supervisord. Feel free to contribute. :-)

However, after the install described in the comment above, you should be able to execute `zendesk-automator`.

**Comment by Skeyelab** [comment]
Great.  Your last comment answered what I was about to ask.  I'm already using supervisord, so this is perfect.  I've never used a gem w/ supervisord, what path should I use to locate where I am running the gem from?

**Comment by andskli** [comment]
On a ubuntu based system it seems to install to `/usr/local/bin`, on my mac it's `/usr/bin`, so I guess that depends on the gem settings.

Alternatively, you could specify it while running `gem install`, see below:

```
  Install/Update Options:
    -i, --install-dir DIR            Gem repository directory to get installed
                                     gems
    -n, --bindir DIR                 Directory where binary files are
                                     located
```

bindir is the one you would be interested in.

**Comment by Skeyelab** [comment]
hopefully last question for you.  Can we use any dynamic text in the yaml?  I'd love to set a due date for a task to be the following day of when the ticket is created, or to be able to add today's date in the body of the ticket created.

**Comment by Skeyelab** [comment]
nevermind, I see it in the readme now...

**Comment by andskli** [comment]
Great. Thanks for using this. Also, feel free to contribute further issues/suggestions :+1:

**Comment by Skeyelab** [comment]
no problem.  here is something you might be interested in: https://github.com/Skeyelab/ZendeskAuditLog2CSV

It exports Zendesk's system audit log to a CSV file.  I need to dig thru a lot of logs from time to time.

I'll add documentation soon
